### ISSUE TITLE
Checklist for March Release

### ISSUE THREAD

**Issue by ariya** [hyperjumptech/symon#142]
ETA: TBD

* [ ] Initial setup upon a fresh installation (#137)
* [ ] Create and configure a new project (#139)
* [ ] Create and configure a new probe (#140)
