### ISSUE TITLE
SyMonika: API for handshake

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/symon#145]
Symon should be able to receive data from Monika instances and manage them.

- [x] Create a new API for the [handshake](https://nicnocquee.github.io/monika/monika-hq#handshake) process.
- [x] Save the configuration to database
- [x] Return a unique string identifying the configuration

**Comment by kevinhermawan** [comment]
#152
