### ISSUE TITLE
SyMonika: Probe's Overview Page

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/symon#148]
## Requirements

User should be able to see details of a probe:

- [ ] Show response time of the probe: average / slowest / fastest. E.g. (0.2s / 0.3s / 0.1s)
- [ ] Uptime/Downtime in percentage.
- [ ] Response time graph for the last two weeks. There is a dropdown to select which instance to display.
- [ ] Latest failed checks: date, time, duration, and the Monika instance
- [ ] The request URL(s)

## Mockup

![Probe Overview Page](https://user-images.githubusercontent.com/311343/117109638-3d8f7700-ad85-11eb-8507-f2ff844d4c95.png)

## Note

- The request section shows up to 2 requests in the probe. If there are more, show "More" button.
- In the response time graph, shows the dropdown to select which instance if there are more than 1 instance for this probe.
