### ISSUE TITLE
SyMonika: Manage Monika instances

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/symon#150]
User should be able to manage Monika instances

- [ ] Show list of connected Monika instances
- [ ] Update notification settings of each instances 
- [ ] Add notification of each instances
- [ ] Remove notification of each instances 

![All Monika Instances Page](https://user-images.githubusercontent.com/311343/116366599-c303ac00-a806-11eb-9033-62770c4b3932.png)

![Empty Instances Page](https://user-images.githubusercontent.com/311343/116366911-137b0980-a807-11eb-823f-df9485025707.png)
